### PR TITLE
Use old readr on windows

### LINKED ISSUE #205: `get_stats19()` sometime fails when reading the same data twice
Not a big deal, but maybe worth exploring what's going on sooner or later: 

``` r
library(stats19)
#> Data provided under OGL v3.0. Cite the source and link to:
#> www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

a17 <- get_stats19(2017, silent = TRUE)
#> date and time columns present, creating formatted datetime column
a17 <- get_stats19(2017, silent = TRUE)
#> Error in utils::unzip(destfile, exdir = file.path(data_dir, exdir)): cannot open file 'C:/Users/Utente/Documents/stats19-data/dftRoadSafetyData_Accidents_2017/Acc.csv': Invalid argument

a18 <- get_stats19(2018, silent = TRUE)
#> date and time columns present, creating formatted datetime column
a18 <- get_stats19(2018, silent = TRUE)
#> date and time columns present, creating formatted datetime column

a19 <- get_stats19(2019, silent = TRUE)
#> date and time columns present, creating formatted datetime column
a19 <- get_stats19(2019, silent = TRUE)
#> Error in utils::unzip(destfile, exdir = file.path(data_dir, exdir)): cannot open file 'C:/Users/Utente/Documents/stats19-data/DfTRoadSafety_Accidents_2019/Road Safety Data - Accidents 2019.csv': Invalid argument

a1719 <- get_stats19(2017:2019, silent = TRUE)
#> Error in utils::unzip(destfile, exdir = file.path(data_dir, exdir)): cannot open file 'C:/Users/Utente/Documents/stats19-data/dftRoadSafetyData_Accidents_2017/Acc.csv': Invalid argument
```

<sup>Created on 2021-07-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

### PR DESCRIPTION
**Pull request by agila5**
TODO, just want to test the GHA. Will fix #205.

### CODE REVIEW

**Comment by agila5** [comment]
Tests have passed 🎉 Just one note: I decided to adopt edition 1 only on windows since the `readr` news says: 

> On Windows open files cannot be deleted as long as a process has the file open. Because `readr` keeps a file open when reading lazily this means you cannot read, then immediately delete the file.

This implies that the user gets slightly different results depending on the OS but, I think, the benefits of the new `readr` + `vroom` approach outweigh this difference. @Robinlovelace what do you think?

**Comment by Robinlovelace** [comment]
Looks great to me and +1 for using the newer and faster approach where possible.

File: R/dl.R [hunk 1]
```diff
@@ -120,10 +120,10 @@ dl_stats19 = function(year = NULL,
       utils::download.file(zip_url, destfile = destfile, quiet = silent)
     }
     if(is_zip_file) {
-      f = file.path(destfile, utils::unzip(destfile, list = TRUE)$Name)
+      f2 = file.path(destfile, utils::unzip(destfile, list = TRUE)$Name)
```
Comment (Robinlovelace) [inline R/dl.R:123]: Reasonable object renaming, sorry for the terse object names, and having thought about it more explicit and longer names would probably better - only issue being when you go over 80 characters on a line. FYI this would not be allowed if we used Rust and the `clippy` code checking tool. Heads up @dabreegster in case it's of interest, this is deep in the codebase that downloads, reads and cleans the STATS19 crash data for the UK.

File: R/read.R [hunk 2]
```diff
@@ -27,6 +27,12 @@ read_accidents = function(year = NULL,
                           data_dir = get_data_directory(),
                           format = TRUE,
                           silent = FALSE) {
+  # Set the local edition for readr.
+  # See https://github.com/ropensci/stats19/issues/205
+  if (.Platform$OS.type == "windows" && utils::packageVersion("readr") >= "2.0.0") {
```
Comment (Robinlovelace) [inline R/read.R:32]: Minimising the impact of the change :+1:

**Review by Robinlovelace — APPROVED** [review]

File: R/read.R [hunk 3]
```diff
@@ -163,6 +169,12 @@ check_input_file = function(filename = NULL,
 # path = file.path(get_data_directory(), f)
 # read_ve_ca(path)
 read_ve_ca = function(path) {
+  # Set the local edition for readr.
+  # See https://github.com/ropensci/stats19/issues/205
+  if (.Platform$OS.type == "windows" && utils::packageVersion("readr") >= "2.0.0") {
+    readr::local_edition(1)
+  }
```
Comment (layik) [inline R/read.R:176]: Is that CodeCov commenting on lines? My goodness. Great effort team `stats19`.

Comment (Robinlovelace) [reply R/read.R:176]: Yes it seems CodeCov now tells you which lines are not tested. Kind of hard to test with the `testthat` package, unless they add a function to try on a different OS mid way through the checks!
